### ISSUE TITLE
Marianas 1.8.1 Errors out

### ISSUE THREAD

**Issue by rhshah** [juberpatel/Marianas#3]
Hi Juber,
I am trying to run the latest release of Marianas (1.8.1) and it errors out:
```
 java -server -Xms8G -Xmx8G -cp $PWD/Marianas-1.8.1.jar org.mskcc.marianas.umi.duplex.fastqprocessing.ProcessLoopUMIFastq  $PWD/test_R1.fastq.gz $PWD/test_R2.fastq.gz 3
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.charAt(String.java:646)
	at org.mskcc.marianas.umi.duplex.fastqprocessing.LoopUMIProcessor.countSupportBases(LoopUMIProcessor.java:95)
	at org.mskcc.marianas.umi.duplex.fastqprocessing.LoopUMIProcessor.process(LoopUMIProcessor.java:57)
	at org.mskcc.marianas.umi.duplex.fastqprocessing.LoopUMIProcessor.<init>(LoopUMIProcessor.java:25)
	at org.mskcc.marianas.umi.duplex.fastqprocessing.ProcessLoopUMIFastq.main(ProcessLoopUMIFastq.java:94)
```

Am I doing something wrong?

Also this is the java version:
```
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```
@ionox0

**Comment by rhshah** [comment]
@juberpatel  my bad solved it
